import type { Metadata } from "next";
import { Geist, Geist_Mono, JetBrains_Mono } from "next/font/google";
import "./globals.css";
import { TooltipProvider } from "@/components/ui/tooltip";
import { Toaster } from "@/components/ui/sonner";
import { ThemeProvider } from "@/components/theme-provider";
// import { getCurrentUser } from "@/lib/services/auth.service";
import UserHydrator from "@/components/hydrator/hydrator-user";
import { user } from "@prisma/client";
import { getCurrentUserService } from "@/lib/services/auth.service";
import getSingleChannelService from "./api/channel/[id]/service";
import { getChannelsService } from "./api/channel/service";
import ChannelsHydrator from "@/components/hydrator/hydrator-channels";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const jetbrainsMono = JetBrains_Mono({
  subsets: ["latin"],
  variable: "--font-jetbrains-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const user = await getCurrentUserService()
  console.log(user.role, "layout")

  const mine = !(user?.role === "SUPER_ADMIN" || user?.role === "ADMIN");
  const channels = await getChannelsService(mine);

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${jetbrainsMono.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <TooltipProvider>
            <UserHydrator user={user}>
              <ChannelsHydrator channels={channels}>

                {children}

              </ChannelsHydrator>
            </UserHydrator>
            <Toaster />
          </TooltipProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
