export const SectionLabels = {
  INTRO: "Intro",
  VERSE: "Verse",
  PRE_CHORUS: "Pre-Chorus",
  CHORUS: "Chorus",
  POST_CHORUS: "Post-Chorus",
  BRIDGE: "Bridge",
  INTERLUDE: "Interlude",
  INSTRUMENTAL: "Instrumental",
  SOLO: "Solo",
  RAP: "Rap",
  HOOK: "Hook",
  REFRAIN: "Refrain",
  BREAKDOWN: "Breakdown",
  OUTRO: "Outro",
  ENDING: "Ending",
  SPOKEN: "Spoken",
  ADLIB: "Adlib",
  OTHER: "Other",
}